//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterConsole {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class TwitterConsoleSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TwitterConsoleSettings defaultInstance = ((TwitterConsoleSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TwitterConsoleSettings())));
        
        public static TwitterConsoleSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lFpIBIY4zobXxpwoxKHRM5CBuCAW3dOeO4dnCu7BVgCmDt1DLa")]
        public string TwitterApiSecret {
            get {
                return ((string)(this["TwitterApiSecret"]));
            }
            set {
                this["TwitterApiSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAAAAAAAAAAAAAAAAAAAAOsxkgEAAAAAr8sfjNxLVURpjWjPINNILQOZlVU%3D0rIZkFvsnQG5eVtUmSQ" +
            "V13z9NNaQnHJu0RBnEV6ZzC9JdqTifG")]
        public string TwitterBearerToken {
            get {
                return ((string)(this["TwitterBearerToken"]));
            }
            set {
                this["TwitterBearerToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DdfG1vF2UD0LKYn7D7yIK6R0k")]
        public string TwitterApiKey {
            get {
                return ((string)(this["TwitterApiKey"]));
            }
            set {
                this["TwitterApiKey"] = value;
            }
        }
    }
}
